<?php
$ID_USER = $_SESSION['LOGINUS_GIS'];
$USERAKSES = $_SESSION['LOGINAKS_GIS'];
$USERNAME = $_SESSION['LOGINUS_GIS'];

$ID_PEMASUKAN="";
$TANGGAL_MASUK_AWAL = date('Y-m-01');
$TANGGAL_MASUK_AKHIR = date('Y-m-t');
$ID_KATEGORI = "";
$ID_BARANG = "";

$ID_KATEGORI_EDIT = "";
$ID_BARANG_EDIT = "";

if (isset($_POST['cari'])) {
    $ID_PEMASUKAN = $_POST['ID_PEMASUKAN'];
    $TANGGAL_MASUK_AWAL = $_POST['TANGGAL_MASUK_AWAL'];
    $TANGGAL_MASUK_AKHIR = $_POST['TANGGAL_MASUK_AKHIR'];
    $ID_KATEGORI = $_POST['ID_KATEGORI'];
    $ID_BARANG = $_POST['ID_BARANG'];

    $getBarang = GetQuery2("SELECT ID_BARANG ID_BARANG,NAMA_BARANG FROM m_barang WHERE STATUS = 1 AND ID_KATEGORI = :ID_KATEGORI", [':ID_KATEGORI' => $ID_KATEGORI]);

    $ID_KATEGORI_EDIT = $ID_KATEGORI;
    $ID_BARANG_EDIT = $ID_BARANG;

    if ($USERAKSES == "User") {
        $query = "SELECT m.*,d.KONDISI KONDISI_KEMBALI,d.FOTO FOTO_KEMBALI,CASE WHEN d.DK = 'D' THEN 'Debit' ELSE 'Kredit' END DK_DESK,d.QTY QTY_KEMBALI,b.ID_BARANG,b.NAMA_BARANG,k.NAMA_KATEGORI,d2.FOTO FOTO_KELUAR,d2.KONDISI KONDISI_KELUAR,REPLACE(d2.QTY,'-','') QTY_KELUAR
        FROM t_pemasukan m
        LEFT JOIN t_persediaan d ON m.ID_PEMASUKAN = d.ID_TRANSAKSI
        LEFT JOIN t_persediaan d2 ON m.ID_PENGELUARAN = d2.ID_TRANSAKSI
        LEFT JOIN m_barang b ON d.ID_BARANG = b.ID_BARANG
        LEFT JOIN m_kategori k ON k.ID_KATEGORI = b.ID_KATEGORI
        WHERE m.`STATUS` = 1 AND m.ID_PEMASUKAN LIKE :ID_PEMASUKAN AND m.TANGGAL_MASUK BETWEEN :TANGGAL_MASUK_AWAL AND :TANGGAL_MASUK_AKHIR AND b.ID_KATEGORI LIKE :ID_KATEGORI AND b.ID_BARANG LIKE :ID_BARANG AND m.CREATED_BY = '$USERNAME'";
    } else {
        $query = "SELECT m.*,d.KONDISI KONDISI_KEMBALI,d.FOTO FOTO_KEMBALI,CASE WHEN d.DK = 'D' THEN 'Debit' ELSE 'Kredit' END DK_DESK,d.QTY QTY_KEMBALI,b.ID_BARANG,b.NAMA_BARANG,k.NAMA_KATEGORI,d2.FOTO FOTO_KELUAR,d2.KONDISI KONDISI_KELUAR,REPLACE(d2.QTY,'-','') QTY_KELUAR
        FROM t_pemasukan m
        LEFT JOIN t_persediaan d ON m.ID_PEMASUKAN = d.ID_TRANSAKSI
        LEFT JOIN t_persediaan d2 ON m.ID_PENGELUARAN = d2.ID_TRANSAKSI
        LEFT JOIN m_barang b ON d.ID_BARANG = b.ID_BARANG
        LEFT JOIN m_kategori k ON k.ID_KATEGORI = b.ID_KATEGORI
        WHERE m.`STATUS` = 1 AND m.ID_PEMASUKAN LIKE :ID_PEMASUKAN AND m.TANGGAL_MASUK BETWEEN :TANGGAL_MASUK_AWAL AND :TANGGAL_MASUK_AKHIR AND b.ID_KATEGORI LIKE :ID_KATEGORI AND b.ID_BARANG LIKE :ID_BARANG";
    }
    
    $params = array(
        ":ID_PEMASUKAN" => "%" . $_POST['ID_PEMASUKAN'] . "%",
        ":TANGGAL_MASUK_AWAL" => $_POST['TANGGAL_MASUK_AWAL'],
        ":TANGGAL_MASUK_AKHIR" => $_POST['TANGGAL_MASUK_AKHIR'],
        ":ID_KATEGORI" => "%" . $_POST['ID_KATEGORI'] . "%",
        ":ID_BARANG" => "%" . $_POST['ID_BARANG'] . "%"
    );

    $getPemasukan = GetQuery2($query, $params);
    $rowBarang = $getBarang->fetchAll(PDO::FETCH_ASSOC);
} else {
    if ($USERAKSES == "User") {
        $query = "SELECT m.*,d.KONDISI KONDISI_KEMBALI,d.FOTO FOTO_KEMBALI,CASE WHEN d.DK = 'D' THEN 'Debit' ELSE 'Kredit' END DK_DESK,d.QTY QTY_KEMBALI,b.ID_BARANG,b.NAMA_BARANG,k.NAMA_KATEGORI,d2.FOTO FOTO_KELUAR,d2.KONDISI KONDISI_KELUAR,REPLACE(d2.QTY,'-','') QTY_KELUAR
        FROM t_pemasukan m
        LEFT JOIN t_persediaan d ON m.ID_PEMASUKAN = d.ID_TRANSAKSI
        LEFT JOIN t_persediaan d2 ON m.ID_PENGELUARAN = d2.ID_TRANSAKSI
        LEFT JOIN m_barang b ON d.ID_BARANG = b.ID_BARANG
        LEFT JOIN m_kategori k ON k.ID_KATEGORI = b.ID_KATEGORI
        WHERE m.`STATUS` = 1 AND TANGGAL_MASUK BETWEEN :TANGGAL_MASUK_AWAL AND :TANGGAL_MASUK_AKHIR AND m.CREATED_BY = '$USERNAME'";       
    } else {
        $query = "SELECT m.*,d.KONDISI KONDISI_KEMBALI,d.FOTO FOTO_KEMBALI,CASE WHEN d.DK = 'D' THEN 'Debit' ELSE 'Kredit' END DK_DESK,d.QTY QTY_KEMBALI,b.ID_BARANG,b.NAMA_BARANG,k.NAMA_KATEGORI,d2.FOTO FOTO_KELUAR,d2.KONDISI KONDISI_KELUAR,REPLACE(d2.QTY,'-','') QTY_KELUAR
        FROM t_pemasukan m
        LEFT JOIN t_persediaan d ON m.ID_PEMASUKAN = d.ID_TRANSAKSI
        LEFT JOIN t_persediaan d2 ON m.ID_PENGELUARAN = d2.ID_TRANSAKSI
        LEFT JOIN m_barang b ON d.ID_BARANG = b.ID_BARANG
        LEFT JOIN m_kategori k ON k.ID_KATEGORI = b.ID_KATEGORI
        WHERE m.`STATUS` = 1 AND TANGGAL_MASUK BETWEEN :TANGGAL_MASUK_AWAL AND :TANGGAL_MASUK_AKHIR";
    }
    
    $params = array(
        ":TANGGAL_MASUK_AWAL" => $TANGGAL_MASUK_AWAL,
        ":TANGGAL_MASUK_AKHIR" => $TANGGAL_MASUK_AKHIR
    );
    $getPemasukan = GetQuery2($query, $params);
}

$kategori = "SELECT ID_KATEGORI,NAMA_KATEGORI FROM m_kategori WHERE STATUS = 1";
$params = array();
$getKategori = GetQuery2($kategori, $params);


$rowPemasukan = $getPemasukan->fetchAll(PDO::FETCH_ASSOC);
$rowKategori = $getKategori->fetchAll(PDO::FETCH_ASSOC);


?>